### ISSUE TITLE
3840*2160分辨率和200%缩放支持

### ISSUE THREAD

**Issue by JC-ProPlus** [SkeathyTomas/genshin_artifact_auxiliary#1]
🤔还没有吗
```
3840 2160
暂不支持该分辨率，请联系作者。
Traceback (most recent call last):
  File "app.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "location.py", line 47, in <module>
NameError: name 'row_A' is not defined
[21316] Failed to execute script 'app' due to unhandled exception!
```

**Comment by SkeathyTomas** [comment]
最新的 commit 里已经适配了 4k 分辨率（手头没有 4k 显示屏不能保证完全没问题），发 release 估计还要等几天。
